config = {
    'guides_3k_file_name': 'data/btCRISPRko.v1_small_3000.xlsx',
    'hamming_dist_path': 'output/hamming_distance.csv',
    'levenshtein_dist_path': 'output/levenshtein_distance.csv',
    'hamming_per_dist_path': 'output/hamming_per_distance.csv',
    'levenshtein_per_dist_path': 'output/levenshtein_per_distance.csv',
    'hamming_dict_dist_2_3_path': 'output/hamming_dict_dist_2_3.csv',
    'levenshtein_dict_dist_2_3_path': 'output/levenshtein_dict_dist_2_3.csv',
    'histograms_path': 'output/histograms',
    'hist_amount_seq_per_dist_hamming': 'output/histograms/hist_amount_seq_per_dist_hamming.png',
    'hist_amount_seq_per_dist_levenshtein': 'output/histograms/hist_amount_seq_per_dist_levenshtein.png',
    'heatmap_hamming_dist': 'output/histograms/heatmap_hamming_dist.jpeg',
    'heatmap_levenshtein_dist': 'output/histograms/heatmap_levenshtein_dist.jpeg',
    'blast_results': 'output/blast_results',
    'sum_amount_for_each_match_for_each_grna_sum_from_20_to_i': '/sum_amount_for_each_match_for_each_grna_sum_from_20_to_i',
    'sum_amount_of_gRNA_with_match_in_bin_x_i': '/sum_amount_of_gRNA_with_match_in_bin_x_i_sum',
    'for_each_match_for_each_grna': '/for_each_match_for_each_grna',
    'drop_grna_that_has_too_many_matches_in_cow_genome': ['2612_nc_guide9542_1', '2795_nc_guide43129_1', '816_NR1D1_5', '974_RERE_4', '1086_SREBF1_3', '1539_ZNF24_4', '1808_ZNF639_3', '567_KLF10_2', '1320_ZBTB25_3', '1785_ZNF614_3', '2237_LOC618268_1'],
    'grna_that_has_too_many_matches_in_cow_genome': '/grna_that_has_too_many_matches_in_cow_genome.csv',
    'gff_file': 'Data/GCF_002263795.2_ARS-UCD1.3_genomic.gff'
}
